# Generated by Django 5.1.1 on 2024-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('recording', models.FileField(blank=True, null=True, upload_to='recordings')),
                ('is_assigned', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
